name:                apple-push
version:             0.0.1.0
synopsis:            Apple Push Notification example

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - apns-http2
  - async
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - data-default
  - http2
  - keys
  - lens
  - lifted-base
  - mmorph
  - mtl
  - network
  - stm
  - stm-chans
  - stm-conduit
  - text
  - time
  - tls
  - x509
  - x509-store
  - x509-validation

default-extensions:
  - FlexibleContexts
  - FlexibleInstances
  - LambdaCase
  - NamedFieldPuns
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - ViewPatterns

ghc-options: -Wall -O2

executables:
  apns-http2-example:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - aeson-qq
      - apns-http2
      - base16-bytestring
      - x509-system
