#!/usr/bin/env bash

set -euo pipefail

host=api.development.push.apple.com
host=api.push.apple.com
port=443
certPath="$APN_CERT_PATH"
keyPath="$APN_KEY_PATH"
deviceToken="$APN_DEVICE_TOKEN"
topic=$APN_TOPIC

set -x
stack exec -- apns-http2-example \
  "$host" \
  "$port" \
  "$certPath" \
  "$keyPath" \
  "$deviceToken" \
  "$topic"
