#!/usr/bin/env bash

set -euo pipefail

host=api.development.push.apple.com
host=api.push.apple.com
topic="$APN_TOPIC"

curl -v \
  -d '{"aps":{"alert":"Hello 3!"}}' \
  -H "$topic"  \
  --http2-prior-knowledge \
  --cert "$APN_PEM_PATH" \
  "https://$host/3/device/$DEVICE_TOKEN"
